// API endpoints
// Note: baseURL is set in client.js, so endpoints should be relative paths
export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  search: {
    create: '/search',
    list: '/search',
    detail: (id) => `/search/${id}`,
    status: (id) => `/search/${id}/status`,
    resumes: (id) => `/search/${id}/resumes`,
    exportExcel: (id) => `/search/${id}/export/excel`,
    exportCsv: (id) => `/search/${id}/export/csv`,
  },
  users: {
    list: '/users',
    detail: (id) => `/users/${id}`,
    update: (id) => `/users/${id}`,
    delete: (id) => `/users/${id}`,
  },
  candidates: {
    getAll: '/candidates',
    get: (resumeId) => `/candidates/resume/${resumeId}`,
    updateStatus: (resumeId) => `/candidates/resume/${resumeId}/status`,
    addTag: (resumeId) => `/candidates/resume/${resumeId}/tags`,
    removeTag: (resumeId, tag) => `/candidates/resume/${resumeId}/tags/${tag}`,
    assign: (resumeId) => `/candidates/resume/${resumeId}/assign`,
    addRating: (resumeId) => `/candidates/resume/${resumeId}/rating`,
    updateNotes: (resumeId) => `/candidates/resume/${resumeId}/notes`,
    setFolder: (resumeId) => `/candidates/resume/${resumeId}/folder`,
    getInteractions: (resumeId) => `/candidates/resume/${resumeId}/interactions`,
    getByStatus: (status) => `/candidates/status/${status}`,
    getByTags: '/candidates/tags',
    getByVacancy: (vacancyId) => `/candidates/by-vacancy/${vacancyId}`,
    getKanban: '/candidates/kanban',
  },
  vacancies: {
    list: '/vacancies',
    create: '/vacancies',
    get: (id) => `/vacancies/${id}`,
    update: (id) => `/vacancies/${id}`,
    updateStatus: (id) => `/vacancies/${id}/status`,
    updateAutoMatching: (id) => `/vacancies/${id}/auto-matching`,
    addCandidate: (id, resumeId) => `/vacancies/${id}/candidates/${resumeId}`,
    removeCandidate: (id, resumeId) => `/vacancies/${id}/candidates/${resumeId}`,
  },
};
